name: page_view_dot_indicator
description: A simple and animated page view indicator in the form of dots, which you can customise color, size, space and duration.
version: 0.0.1
author: Douglas Iacovelli
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: