name: page_view_dot_indicator
description: A simple and animated page view indicator in the form of dots, which you can customise color, size, space and duration.
version: 0.0.1
homepage: https://github.com/douglasiacovelli/page_view_dot_indicator
repository: https://github.com/douglasiacovelli/page_view_dot_indicator


environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.10.0-nullsafety.1

flutter: