on: pull_request
jobs:
  pr-verification:
    name: PR verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'
      - name: Flutter pub get
        run: flutter pub get
      - name: "[Example] Linter"
        working-directory: ./example
        run: flutter analyze
      - name: "[Lib] Linter"
        run: flutter analyze
      - name: "[Lib] Tests"
        run: flutter test
